config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  get '/about', to: 'about#index'
  get '/about/:team_member_id', to: 'about#show', as: 'team_member'

  resources :projects, only: [:show]
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                         :integer          not null, primary key
#  title                      :string
#  short_title                :string
#  meta_description           :string
#  fb_title                   :string
#  fb_description             :string
#  link                       :string
#  release_date               :date
#  summary                    :text
#  body                       :text
#  weight                     :integer          default(0)
#  highlighted                :boolean
#  published                  :boolean          default(FALSE)
#  client_id                  :integer
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  cover_image_file_name      :string
#  cover_image_content_type   :string
#  cover_image_file_size      :integer
#  cover_image_updated_at     :datetime
#  project_logo_file_name     :string
#  project_logo_content_type  :string
#  project_logo_file_size     :integer
#  project_logo_updated_at    :datetime
#  project_image_file_name    :string
#  project_image_content_type :string
#  project_image_file_size    :integer
#  project_image_updated_at   :datetime
#  grid                       :integer
#  slug                       :string
#  post_url                   :string
#  post_title                 :string
#  short_link                 :string
#  author                     :string
#

class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :short_title, use: :slugged

  acts_as_list column: 'weight'

  belongs_to :client
  has_many :text_blocks, dependent: :destroy
  has_many :opinions, dependent: :destroy
  has_one :map, dependent: :destroy
  has_one :video, dependent: :destroy
  has_one :block, dependent: :destroy

  accepts_nested_attributes_for :text_blocks, allow_destroy: true
  accepts_nested_attributes_for :opinions, allow_destroy: true
  accepts_nested_attributes_for :map, allow_destroy: true
  accepts_nested_attributes_for :video, allow_destroy: true
  accepts_nested_attributes_for :block, allow_destroy: true

  has_attached_file :project_logo,
    styles: { medium: "300x110>" },
    default_url: ActionController::Base.helpers.image_path('missing.png')
  has_attached_file :cover_image,
    styles: { thumb: "250x250", medium: "512x512>", large: "1660x800>" },
    default_url: ActionController::Base.helpers.image_path('missing.png')
  has_attached_file :project_image,
    styles: { thumb: "250x250", medium: "512x512>", large: "1660x800>" },
    default_url: ActionController::Base.helpers.image_path('missing.png')

  validates_attachment_content_type :project_logo, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :cover_image, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :project_image, content_type: /\Aimage\/.*\z/
  validate :valid_text_block
  validate :valid_block
  validate :valid_opinions

  class << self
    def options_for_grid
      [1, 2, 3]
    end
  end

  def next
    self.class.find_by(weight: weight + 1)
  end

  def prev
    self.class.find_by(weight: weight - 1)
  end

  private

  def should_generate_new_friendly_id?
    short_title_changed?
  end

  def valid_text_block
    if text_blocks.present?
      sides = text_blocks.pluck(:text_side)

      unless sides.size == sides.uniq.size
        errors.add(:text_blocks, "must only contain one block with 'Text side' left and one block with 'Text side' right.")
      end
    end
  end

  def valid_block
    if block.present?
      if block.block_modules.present?
        positions = block.block_modules.pluck(:position)

        unless positions.size == positions.uniq.size
          errors.add(:block_modules, "shouldn't have repeated positions.")
        end
      else
        errors.add(:block, "must have at least one block module.")
      end
    end
  end

  def valid_opinions
    if opinions.present?
      positions = opinions.pluck(:position)

      if opinions.size > 3
        errors.add(:opinions, "- 3 max.")
      end

      unless positions.size == positions.uniq.size
        errors.add(:opinions, "shouldn't have repeated positions.")
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.friendly.find(params[:id])
    @next_project = @project.next if @project.present?
  end
end

app/views/projects/_highlighted_list.html.erb
<div class="row" id="projects">
  <div class="grid-sm-14 grid-lg-12 offset-lg-1">
    <% @highlighted_projects.each do |p| %>
      <article class="m-project-card" style="background-image: url(<%= p.project_image.url(:large) %>)">
        <%= link_to "", project_path(p.slug), class: "cover-link" %>
        <div class="veil"></div>
        <div class="m-project-content">
          <%= image_tag p.project_logo.present? ? p.project_logo.url(:medium) : p.client.logo_white.url %>
          <h1><%= p.title + '.' %></h1>
          <p class="description"><%= p.summary %></p>
          <%= link_to "Read more", project_path(p.slug), class: "btn-third" %>
        </div>
     </article>
    <% end%>
  </div>
</div>

app/views/projects/_list.html.erb
<div class="row" id="projects">
  <div class="grid-sm-14 grid-lg-12 offset-lg-1">
    <ul class="m-project-grid">
      <% @projects.each do |p| %>
        <li class="is-grid-<%= p.grid %>" style="background-image: url(<%= p.project_image.url(:large) %>)">
          <%= link_to project_path(p.slug), class: 'm-project-grid-link' do %>
            <div class="veil"></div>
            <div class="m-project-grid-content">
              <%= image_tag p.project_logo.present? ? p.project_logo.url(:medium) : p.client.logo_white.url %>
              <h2><%= p.short_title %></h2>
            </div>
          <% end %>
        </li>
      <% end%>
    </ul>
  </div>

  <div class="grid-sm-14 grid-lg-12 offset-lg-1">
    <div class="m-all-projects">
      <a class="btn allProjectsLink" href="#">See all projects</a>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% body_class "is-project-detail-page" %>
<div class="l-main">
  <section class="m-project-detail">
    <header class="m-project-detail-header" style="background-image: url(<%= @project.cover_image.url %>)">
      <div class="veil"></div>
      <div class="row">
        <div class="grid-sm-14 grid-lg-12 offset-lg-1">
          <h1><%= @project.title + '.' %></h1>
          <p class="summary"><%= @project.summary %></p>
        </div>
      </div>
    </header>

    <%= link_to "Check it online", @project.link, class: "btn btn-check", target: "_blank" if @project.link %>

    <div class="m-project-detail-content">
      <div class="row">
        <div class="grid-sm-8 grid-md-8 grid-lg-8 offset-lg-1">
          <p><%= raw @project.body %></p>
        </div>
        <div class="grid-sm-5 grid-md-5 grid-lg-4 offset-sm-1 offset-md-1 offset-lg-1">
          <div class="client-info">
            <%= image_tag @project.client.logo.url(:medium), class: "m-project-client-logo" %>
            <h2><%= @project.client.name if @project.client && @project.client.name%></h2>
            <p class="date"><%= format_release_date(@project.release_date) if @project.release_date %></p>
            <%= link_to "Check it online", @project.link, class: "btn", target: "_blank" if @project.link %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <% if @project.text_blocks.present? %>
    <% @project.text_blocks.each do |text_block| %>
      <section class="m-project-detail-article is-<%= text_block.text_side %>">
        <div class="row sameheight is-grid-centered">
          <% if text_block.text_side == 'left' %>
            <div class="grid-sm-14 grid-lg-5 offset-lg-1 is-grid-centered">
              <div class="m-project-article-content">
                <h2><%= text_block.title %></h2>
                <p><%= text_block.description %></p>
              </div>
            </div>
          <% end %>

          <div class="grid-sm-14 grid-lg-8">
            <%= image_tag text_block.image.url, alt: "#{@project.short_title}-details" %>
          </div>

          <% if text_block.text_side == 'right' %>
            <div class="grid-sm-14 grid-lg-5">
              <div class="m-project-article-content">
                <h2><%= text_block.title %></h2>
                <p><%= text_block.description %></p>
              </div>
            </div>
          <% end %>
        </div>
      </section>
    <% end %>
  <% end %>

  <% if @project.block.present? && @project.block.block_modules.present? %>
    <section class="m-project-detail-blocks">
      <div class="row uncollapse">
        <div class="grid-sm-14 grid-lg-12 offset-lg-1">
          <h2><%= @project.block.title %></h2>
        </div>
      </div>

      <div class="row uncollapse">
        <% @project.block.block_modules.each_with_index do |b, i| %>
          <div class="grid-sm-14 grid-md-4 grid-lg-4 <%= i == 0 ? 'offset-lg-1' : '' %>">
            <div class="thumb">
              <%= image_tag b.image.url, alt: "#{@project.short_title}-details" %>
            </div>
            <p><%= b.description %></p>
          </div>
        <% end %>
      </div>
    </section>
  <% end %>

  <% if @project.map.present? %>
    <section class="m-project-detail-iframe">
      <div class="row">
        <div class="grid-sm-14 grid-lg-12 offset-lg-1">
          <h2><%= @project.map.title %></h2>

          <div class="m-project-iframe">
            <div class="m-project-iframe-content">
              <iframe src="<%= @project.map.url %>" frameborder="0"></iframe>
            </div>
          </div>

          <p><%= @project.map.description %></p>
        </div>
      </div>
    </section>
  <% end %>
  
  <% if @project.video.present? %>
    <section class="m-project-detail-video <%= @project.video.style %>">
      <div class="row">
        <div class="grid-sm-14 grid-lg-10 offset-lg-2">
          <div class="video-box">
            <iframe src=<%= @project.video.url %> frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </section>
  <% end %>

  <% if @project.post_title.present? && @project.post_url.present? %>
    <section class="m-project-blog">
      <div class="row">
        <div class="grid-sm-14 grid-lg-12 offset-lg-1">
          <article class="m-post-card">
            <div class="m-post-card-content">
              <h1>Stay tuned.</h1>
              <h2><%= link_to(@project.post_title, @project.post_url) %></h2>
              <%= link_to('Read our blog', @project.post_url, class: 'btn') %>
            </div>
          </article>
        </div>
      </div>
    </section>
  <% end %>

  <% if @project.opinions.present? %>
    <section class="m-project-opinions">
      <h2>What are people saying about it?</h2>

      <div class="row uncollapse sameheight">
        <% @project.opinions.each do |opinion| %>
          <div class="grid-sm-14 grid-lg-4">
            <div class="m-project-opinion-item">
              <div>
                <% if opinion.thumbnail.present? %>
                  <p class="m-project-opinion-photo">
                    <%= image_tag opinion.thumbnail.url, alt: "#{@project.short_title}-opinion" %>
                  </p>
                <% end %>
                <p class="m-project-opinion-text">
                  <%= opinion.title %>
                </p>
                <p class="m-project-opinion-autor">
                  <%= link_to(opinion.author_name, opinion.author_url) %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </section>
  <% end %>

  <% if @project.link && @project.short_link %>
    <footer class="m-project-detail-footer">
      <div class="row sameheight">
        <div class="grid-sm-14 is-grid-centered m-project-url">
          <a href="<%= @project.link %>" target="_blank" class="link-cover"></a>
          <div><p><%= @project.short_link %></p></div>
          <div><%= link_to('Check it online', @project.link, target: '_blank', class: 'btn') %></div>
        </div>
      </div>
    </footer>
  <% end %>

  <section class="m-message">
    <div class="row">
      <div class="grid-sm-14 grid-lg-12 offset-lg-1">
        <p>Get in touch.</p>
        <%= link_to('Contact us', about_path(anchor: 'contact'), class: 'btn') %>
      </div>
    </div>
  </section>

  <% if @next_project.present? %>
    <section class="m-project-detail-next" style="background-image: url(<%= @next_project.project_image.url %>)">
      <div class="veil">
      </div>
      <div class="row">
        <div class="grid-sm-14 grid-lg-12 offset-lg-1">
          <p><%= @next_project.title %></p>
          <h1><%= link_to(@next_project.title, project_path(@next_project)) %></h1>
        </div>
      </div>
    </section>
  <% end %>

</div>